In [2]:
import numpy as np

In [8]:
def print_obj(obj, name):
    print(f"{name}:\n{obj}\n")
    
def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

## Scalars, Vectors, Matrices

In [9]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [10]:
print_obj(a, 'a') # Scalar
print_obj(b, 'b') # Vector
print_obj(c, 'c') # Matrix

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [11]:
print_obj(a.ndim, 'a.ndim')
print_obj(b.ndim, 'b.ndim')
print_obj(c.ndim, 'c.ndim')

a.ndim:
0

b.ndim:
1

c.ndim:
2



In [12]:
print_obj(a.shape, 'a.shape')
print_obj(b.shape, 'b.shape')
print_obj(c.shape, 'c.shape')

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)



## Tensor(N-dimensional array)

In [13]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]],[[7.,8.,9.],[10.,11.,12.]]])
e = np.array([])

Quiz : What is the shape of [[[1],[2],[3]],[[4],[5],[6]]]?
Ans = (2, 3, 1)

## Defining Numpy Arrays

In [14]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
a = np.zeros((2, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
a = np.full((2, 5), 5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [18]:
a = np.random.random((2,3,4))
a

array([[[0.43002602, 0.33148303, 0.26756395, 0.90407409],
        [0.69898655, 0.3357748 , 0.52295414, 0.27912687],
        [0.69415891, 0.9363583 , 0.73160059, 0.52643847]],

       [[0.31408362, 0.87320908, 0.46344137, 0.55411146],
        [0.52030595, 0.86106615, 0.25670544, 0.54342544],
        [0.13595337, 0.29711165, 0.00318119, 0.17077775]]])

In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = np.arange(10).astype('float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
a = np.arange(10).reshape((5, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Quiz : Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0   
a = np.arange(24).reshape((4,3,2)).astype('float')

## Indexing & Slicing

In [23]:
# Indexing and slicing a vector
a = np.arange(10)
print_obj(a, 'a')


a:
[0 1 2 3 4 5 6 7 8 9]



In [24]:
print_obj(a[0], 'a[0]')
print_obj(a[1], 'a[1]')
print_obj(a[-1], 'a[-1]')
print_obj(a[-3], 'a[-3]')

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7



In [25]:
print_obj(a[0:10], 'a[0:10]')
print_obj(a[0:], 'a[0:]')
print_obj(a[:10], 'a[:10]')
print_obj(a[:], 'a[:]')

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]



In [26]:
print_obj(a[7:], 'a[7:]')
print_obj(a[:5], 'a[:5]')
print_obj(a[2:5], 'a[2:5]')

a[7:]:
[7 8 9]

a[:5]:
[0 1 2 3 4]

a[2:5]:
[2 3 4]



Quiz : What is a a[-4:]?   
Quiz : What is a a[:-8]?

In [27]:
print_obj(a[0:10:2], 'a[0:10:2]')
print_obj(a[0:10:3], 'a[0:10:3]')
print_obj(a[2:6:3], 'a[2:6:3]')

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]



In [28]:
print_obj(a[::-1], 'a[::-1]')
print_obj(a[8:5:-1], 'a[8:5:-1]')
print_obj(a[8:5], 'a[8:5]')

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]



Quiz : Create [9, 6, 3] using a.

In [30]:
#Indexing a matrix
a = np.arange(9).reshape((3, 3))
print_obj(a, 'a')
print_obj(a[0][0], 'a[0][0]')
print_obj(a[0,0], 'a[0,0]')
print_obj(a[1,1], 'a[1,1]')

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4



Quiz : How to access the last row?   
Quiz : How to access the second column?   
Quiz : How to create [8,5] using a?

In [33]:
# Indexing and slicing a 3D tensor
a = np.arange(4 * 3 * 2).reshape((4, 3, 2))
print_obj(a, 'a')
print_obj(a[2, 1, 0], 'a[2,1,0]')

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2,1,0]:
14



Quiz : What would be a[0]?   
Quiz : What would be a[0, 1]?   
Quiz : Create [[0, 2, 4], [6, 8, 10]]

In [34]:
# Conditional indexing
a = np.arange(3 * 2).reshape((3, 2))
print_obj(a, 'a')

idx = a % 2 == 0
print_obj(idx, "idx")

a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[ True False]
 [ True False]
 [ True False]]



Quiz : How would you create [3,4,5] using a?

In [35]:
# Taking a specific elements from a vector
a = np.arange(10)
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")

a[idx]:
[0 2 3]



In [37]:
#Taking specific elements from a tensor
a = np.arange(24).reshape((6, 4))
print_obj(a, "a")

print_obj(a[:,[0,2,3]], "a[idx]")
print_obj(a[[0,2,3], :], "a[idx]")

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[idx]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[idx]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]



In [38]:
idx = ((0,0,1,5),(1,2,0,3))
print_obj(a[idx], "tuple indexing")
idx = np.array([[0,0,1,5],[1,2,0,3]])
print_obj(a[idx], "ndarray indexing")

tuple indexing:
[ 1  2  4 23]

ndarray indexing:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]



In [39]:
# Ellipsis
a = np.arange(288).reshape((2,3,2,2,4,-1))
print_obj(a.shape, "a.shape")

print_obj(a[1,:,:,:,:,2], "Plain indexing")
print_obj(a[1,...,2], "Ellipsis")

a.shape:
(2, 3, 2, 2, 4, 3)

Plain indexing:
[[[[146 149 152 155]
   [158 161 164 167]]

  [[170 173 176 179]
   [182 185 188 191]]]


 [[[194 197 200 203]
   [206 209 212 215]]

  [[218 221 224 227]
   [230 233 236 239]]]


 [[[242 245 248 251]
   [254 257 260 263]]

  [[266 269 272 275]
   [278 281 284 287]]]]

Ellipsis:
[[[[146 149 152 155]
   [158 161 164 167]]

  [[170 173 176 179]
   [182 185 188 191]]]


 [[[194 197 200 203]
   [206 209 212 215]]

  [[218 221 224 227]
   [230 233 236 239]]]


 [[[242 245 248 251]
   [254 257 260 263]]

  [[266 269 272 275]
   [278 281 284 287]]]]



## Math Operations

In [41]:
# Basic Operations
a = np.arange(6).reshape((3,2))
b = np.ones((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a + b, "a + b")
print_obj(a - b, "a - b")
print_obj(a * b, "a * b")
print_obj(a / b, "a / b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a + b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a - b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a * b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a / b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

